version: '3'
services:
  mongo:
    image: mongo:3.6
    ports:
      - "27001:27017"
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  web:
    build: .
    ports:
     - "8080:8080"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test
    links:
     - mongo
    depends_on:
     - mongo
    volumes:
     - .:/starter
     - /starter/node_modules
